apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-opt-pvc
spec:
# storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  volumes:
    - name: ubuntu-opt-vol
      persistentVolumeClaim:
        claimName: ubuntu-opt-pvc
  containers:
    - name: ubuntu
      image: ubuntu
      volumeMounts:
        - name: ubuntu-opt-vol
          mountPath: "/opt"
      resources:
        limits:
          memory: "32000Mi"
          cpu: "24000m"
        requests:
          memory: "16000Mi"
          cpu: "10000m"
      command: ["/bin/sh","-c"]
      args:
        - apt-get update -y;
          apt-get install wget iputils-ping net-tools default-jdk less -y;
          apt-get install lsb-release curl gpg -y;
          curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg;
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list;
          apt-get update -y;
          apt-get install memtier-benchmark redis-tools -y;
          sleep infinity;

  hostNetwork: false
  dnsPolicy: ClusterFirstWithHostNet
